# Site information
site_name: "Python Workshop"
site_author: Luca Capone
site_description: "Material for Python Bootcamp"
# site_url:

# Repository
repo_name: luca-capone/workshop
repo_url: "https://github.com/luca-capone/workshop"
edit_uri: blob/main/docs/
use_directory_urls: false

# Theme configuration
theme:
  name: material
  features:
    - announce.dismiss       # allows users to dismiss announcements
    - content.action.edit    # add an edit button to pages
    - content.action.view    # add a View source button to pages
    - content.code.annotate  # enable annotations for code blocks
    - content.code.copy      # add a copy button to code blocks
    - content.tooltips       # add tooltips to provide additional information.
    - navigation.footer      # enables a footer in the navigation area
    - navigation.indexes     # automatically generate index pages for sections
    - navigation.sections    # divide the navigation into sections
    - navigation.tabs        # add tabs
    - navigation.top         # add a button to scroll to the top of the page
    - search.highlight       # highlight search terms
    - search.share           # allow sharing search results
    - search.suggest         # search autocompletion
    - toc.follow             # table of contents actively follows the reading progress
    # - toc.integrate          # integrate the table of contents into the navigation
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

plugins:
  - mkdocs-jupyter:
      execute: True


# Markdown extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true



validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  nav:
    absolute_links: ignore

nav:
  - Home: home.md
  - Setup: setup.md
  - Programma: schedule.md
  - Materiale:
    - Introduzione: material/00_introduction.md
    - Nozioni fondamentali: material/01_fundamentals.md
    - Flusso di controllo: material/02_control_flow.md
    - Funzioni: material/03_functions.md
    - Classi: material/04_classes.md
    - Ecosistema: material/05_ecosystem.md
  - Esercizi: notebooks/exercise_1.ipynb

  - About: about.md