# Site information
site_name: "Python Workshop"
site_author: Luca Capone
site_description: "Material for Python Bootcamp"
site_url: https://luca-capone.github.io/workshop/

# Repository
repo_name: luca-capone/workshop
repo_url: "https://github.com/luca-capone/workshop"
edit_uri: blob/main/docs/
use_directory_urls: false

# Theme configuration
theme:
  name: material
  features:
    - announce.dismiss # allows users to dismiss announcements
    - content.action.edit # add an edit button to pages
    - content.action.view # add a View source button to pages
    - content.code.annotate # enable annotations for code blocks
    - content.code.copy # add a copy button to code blocks
    - content.code.select # include a button to allow for the selection of line ranges by the user
    - content.tooltips # add tooltips to provide additional information.
    - navigation.footer # enables a footer in the navigation area
    - navigation.indexes # automatically generate index pages for sections
    - navigation.sections # divide the navigation into sections
    - navigation.tabs # add tabs
    - navigation.top # add a button to scroll to the top of the page
    - search.highlight # highlight search terms
    - search.share # allow sharing search results
    - search.suggest # search autocompletion
    - toc.follow # table of contents actively follows the reading progress

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: material/git
    logo: material/language-python

plugins:
  - search
  - mkdocs-jupyter:
      execute: True
      include_source: True
  - print-site

# Markdown extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  nav:
    absolute_links: ignore

nav:
  - Home: index.md
  - Setup: setup.md
  - Programma: schedule.md
  - Materiale:
      - Introduzione: material/introduction.md
      - Nozioni fondamentali: material/fundamentals.md
      - Collezioni: material/collections.md
      - Flusso di controllo: material/control_flow.md
      - Funzioni: material/functions.md
      - Classi: material/classes.md
      - Ecosistema: material/ecosystem.md
  - Soluzione: notebooks/solutions/bank.ipynb
  - About: about.md
